steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone https://github.com/sushantsc2014/Git_to_Jenkins.git
    cd Git_to_Jenkins  
    git checkout feature1
  id: 'To check conflicts'

# Specify the logs bucket
logsBucket: 'gs://etl-demo-dataproc-temp-f08983'

# Substitute 'your-username/your-repo' with your actual GitHub repository details
# Substitute 'your-logs-bucket' with the name of your Cloud Storage bucket for logs