steps:
  # Step 1: Pull the code from the feature1 branch
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --single-branch --branch feature1 https://github.com/sushantsc2014/Git_to_Jenkins.git .
  
  # Step 2: Copy the files to the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        '-m',
        'cp',
        '-r',
        '.',
        'gs://f08983-dev-repo'
      ]

# Substitute 'your-username/your-repo' with your actual GitHub repository details